### ISSUE TITLE
Bedrock server connection issues

### ISSUE THREAD

**Issue by AS1624** [crafting-for-christ/Issues#36]
there is currently no way to join the bedrock sever. I typed the IP address multiple times, and can't join

**Comment by Venomous-Viper1** [comment]
Make sure you are using the correct IP and Port. It should be IP: bedrock.craftingforchrist.net Port: 4056.

**Comment by AS1624** [comment]
thank you. also, quick question: how active is the server currently, and is your server welcoming to LGBTQ+ people

**Comment by Venomous-Viper1** [comment]
We are welcoming to all people. If you have any more questions ask in our discord. https://discord.com/invite/fGWNchS.
