### ISSUE TITLE
swatica

### ISSUE THREAD

**Issue by s4sutler100** [crafting-for-christ/Issues#38]
i logged on and there was a swastika on my property.
![image](https://github.com/craftingforchrist/Issues/assets/16606451/bb3e51c7-91ec-47ea-aa96-0b9ab15aa7b7)

**Comment by s4sutler100** [comment]
I removed it but could you run a co i?

**Comment by benrobson** [comment]
Thanks for this. I will get the staff to have a look into it.

**Comment by benrobson** [comment]
This has been dealt with by staff. Closing this now, thanks for the report.
