### ISSUE TITLE
disrescpipt

### ISSUE THREAD

**Issue by Mos-es** [crafting-for-christ/Issues#39]
h someone put a german swash cross infront of my church .
have removed most of it left bottom part still on tree.
i want to pray thr love of Jesus oer them as they need it .
so i want to place a sign with there name and prayer on it
so dont punish them as want them to see the Love of Jesus
![2023-12-26_21 41 34](https://github.com/craftingforchrist/Issues/assets/150672943/9bca1a40-2dd9-483e-b663-b0943aa0ed4a)
![2023-12-28_22 07 06](https://github.com/craftingforchrist/Issues/assets/150672943/dd6f23fa-fd1e-4e74-a8f1-052938bb9170)

**Comment by benrobson** [comment]
Hey thanks for this. 
I will inform the staff of this.

**Comment by benrobson** [comment]
This user was punished earlier last week for doing this at another users base. 
Resolved.
