### ISSUE TITLE
loss of claim block still not fixed

### ISSUE THREAD

**Issue by Mos-es** [crafting-for-christ/Issues#40]
some time ago we lost all claim blocks and when i tried to claim it said i had minus 17,000 claim blocks,  so wasn't able to claim more blocks, as i have been playing has now come down to minus 13000 claims/ and  i am sure i had a few thousand claim blocks up my sleeve

Amastar also said he also lost his claim blocks

**Comment by benrobson** [comment]
Thanks for this, I am looking into this issue as this has been ongoing.

**Comment by benrobson** [comment]
This should be fixed for you now.
