### ISSUE TITLE
i cant get my grave in someone elses claim

### ISSUE THREAD

**Issue by Bladeblade202006** [crafting-for-christ/Issues#41]
i know this is a well known issue but am tired of it am sure venny is to having to log on every few hours to get my grave back and most of the people here are tired of it as well please do fix it if you cant atleast just make it so we can get our graves back without having to walk all the way over there

**Comment by benrobson** [comment]
Thanks for your ticket. 
I am aware this is an ongoing issue and I'll be looking into a permanent fix.

**Comment by benrobson** [comment]
This should be fixed in the new world reset/update. Please try again and reopen if you have issues.
